#!/bin/bash
cd "${0%/*}" || exit 1
if [ -z "$CUTCELL_IBM_DIR" ]; then source etc/bashrc; fi
wclean libso src/cutCellIBM
wclean applications/utilities/ibmSetGeometry
wclean applications/utilities/ibmOrderTest
wclean applications/solvers/ibmSimpleFoam
wclean applications/solvers/ibmPimpleFoam
rm -rf platforms
